name: android_rpc
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  sms_repository:
    path: ./packages/sms_repository
  android_rpc_server:
    path: ./packages/android_rpc_server
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0

flutter:
  uses-material-design: true
